name: Deploy to production
on: [push]
jobs:

  build:
    name: Build
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd websocket-chat-frontend
          git pull
          cd ..
          sudo docker-compose stop node
          sudo docker container prune -f
          sudo docker rmi ubuntu_node -f
          sudo docker-compose up
          echo "Frontend deployed to production \n" >> deploy.log
