name: Deploy
on: [push]
jobs:

  build:
    name: Deploy to production
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd websocket-chat-frontend
          git pull
          cd ..
          sudo docker-compose stop node
          sudo docker container prune -f
          sudo docker rmi ubuntu_node -f
          sudo docker-compose up -d
          echo "Frontend deployed to production \n" >> deploy.log
